language: java

dist: trusty

jdk:
  - oraclejdk8

notifications:
  email: 
    recipients:
      - gary@sourceauditor.com
    on_success: change
    on_failure: always
    
addons:
  sonarcloud:
    organization: "spdx"
    
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar